global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.144.0.12:9100']